ALTER TABLE "OfficialDutyRequest"
  ADD COLUMN IF NOT EXISTS "sentByType" TEXT NOT NULL DEFAULT 'SENIOR',
  ADD COLUMN IF NOT EXISTS "ownerName" TEXT,
  ADD COLUMN IF NOT EXISTS "approvalMode" TEXT NOT NULL DEFAULT 'TWO_STEP';

ALTER TABLE "OfficialDutyRequest"
  ALTER COLUMN "sentById" DROP NOT NULL;
